### PR TITLE
Icons

### PR DESCRIPTION
**Pull request by bellma-lilly**
Support for custom icons

### CODE REVIEW

**Comment by bellma-lilly** [comment]
I'm not sure why these conflicts are showing up.  They are for code that was already merged from my last pull request.

**Comment by YsoSirius** [comment]
You are using `str_match` and `str_subset` in `list-to-tags.R` from the package `stringr`.  But it is not defined in the Namespace or in the Description. Maybe including that might help?

**Comment by trafficonese** [comment]
Something is missing. Before these conditions you should put
```
      if (is.na(iconGroup[2])){
        iconGroup[2] = "fa fa-"
      }
```
Otherwise missing values will be possible and function will fail.

**Comment by trafficonese** [comment]
Something is missing. Before these conditions you should put
```
      if (is.na(iconGroup[2])){
        iconGroup[2] = "fa fa-"
      }
```
Otherwise missing values will be possible and function will fail.

**Comment by trafficonese** [comment]
By adding the following before the conditions, will make it work for single icon names. Otherwise a missing value error will occur.
```
      if (is.na(iconGroup[2])){
        iconGroup[2] = "fa fa-"
      }
```

**Comment by bellma-lilly** [comment]
@trafficonese @YsoSirius Please checkout my new pull request #52 that fixes hyphens (and it's a cleaner diff)

**Pull request closed without merging**
