### PR TITLE
Plugin support added searchtime

### PR DESCRIPTION
**Pull request by YsoSirius**
sort, unique, contextmenu, state and wholerow plugin support. 
Added searchtime to the initSearch function, to be able to delay searching.

This adresses issues #19 , #43.

Not sure about the state-plugin working correctly with the updateTree function though. I think the state gets messed up somehow and will be lost for the next refresh.
For a normally rendered Tree (without the use of `updateTree`) it should work fine.

### CODE REVIEW

**Comment by YsoSirius** [comment]
The contextmenu is not reactive anymore. Should be adapted or removed from PR until fixed

**Comment by YsoSirius** [comment]
- contextmenu works with this commit, but "id's" will not be set anymore. Is that only relevant for `get_selected(tree, "classid")` ?

- Also `contextmenu` and `checkbox` cannot be used together yet, as it will throw an error, when a new node is created on an uncollapsed parent or when no children are at hand. Then this error appears:

> Error in attr(ret, "stselected") <- json$state$selected : 
>   attempt to set an attribute on NULL

- I removed the tests, since they all used the `listToTags` function

**Comment by YsoSirius** [comment]
This should fix the color problem #54. 
`stclass` colors the a-tags and `liclass` colors the li-tag.

An example is added aswell in `inst/examples/16-contextmenu/`

**Comment by YsoSirius** [comment]
It also fixes #57

**Comment by bellma-lilly** [comment]
These are great additions; however, there are too many to review and test in a single pull request. Can you pull the major changes out into multiple PR's?  If so, I will add these asap.

**Pull request closed without merging**
