### PR TITLE
callbacks for set_state/refresh optional

### LINKED ISSUE #78: get_selected() does not change when tree is updated with updateTree()
This issue is in reference to a [question](https://stackoverflow.com/questions/56555281/r-shiny-updating-shinytree-node-selections/56556146?noredirect=1#comment99695083_56556146) I had posted on SE.

The app below contains a shinyTree, a reset button (`Reset nodes`) and a print output `Selected nodes`, which returns a list of selected nodes using `get_selected`. 

Here is a screenshot of the tree on start-up:

image

No nodes are selected so `get_selected` returns an empty list().

When I make a selection, e.g. node `a`, `get_selected` correctly returns that selection:

image

When I click `Reset nodes`, the node selections are cleared in the tree UI but the list returned by `get_selected` does not change to reflect this:

image

**I would expect `get_selected` to return `list()` when I click `Reset nodes`.** 

Here is the reprex:

```
library(shiny)
library(shinyTree)

tree = list(a=list(a1=1,a2=2) , b="b") 

tree = lapply(tree, function(x) structure(x, stopened = T))

ui <- fluidPage(
  sidebarLayout(
    sidebarPanel(
      actionButton('reset', 'Reset nodes')
    ),
    mainPanel(
      shinyTree("tree", ),
      hr(),
      "Selected nodes:",
      verbatimTextOutput("idSelected")#,
    )
  )
)

# server

server <- function(input, output, session) {
  
  output$tree = renderTree({
    
    tree
    
  })
  
  
  output$idSelected <- renderPrint({
    str(get_selected(input$tree, format = "classid"))
  })
  
  
  # An observer is used to trigger a tree update when reset is clicked.
  observeEvent(input$reset, {
    
    updateTree(session,"tree", data = tree)
    
    print(get_selected(input$tree, format = "classid"))
  })
}

shinyApp(ui, server)
```

I was wondering if this feature was intended or if I was modelling the tree incorrectly?

### PR DESCRIPTION
**Pull request by trafficonese**
A follow up for PR #80, where it is now optional to include the **set_state.jstree** or **refresh.jstree** callbacks.
That should close #78 if either of the 2 lines is included:
```
options(shinyTree.setState = TRUE)
options(shinyTree.refresh = TRUE)
```
All the callbacks that are necessary for the contextmenu, will now only be included if `contextmenu = TRUE`.

I also wrote some small initial tests. I am not sure how to test the interactive parts? Is there some possiblity to do that?

### CODE REVIEW

**Comment by trafficonese** [comment]
I dont know if there is already a `covr` project for that repo, but I added it to travis and the Readme to see the test coverage and other infos.

**Comment by trafficonese** [comment]
Maybe `shinytest` could be used for further tests.
https://www.r-bloggers.com/unit-testing-shiny-apps-using-testthat/

**Comment by bellma-lilly** [comment]
I'm trying to test this, but I'm not clear how to use it. Please create an example that shows what these options do.

**Comment by trafficonese** [comment]
You can look at the example given in #78. 
You have to select a node first and then hit `Reset nodes`.

Without any options set to TRUE, the print Output should still contain the selected node.
With one of the options (`shinyTree.setState, shinyTree.refresh`) set to TRUE, the print output should return to `list()`:

**Comment by thothal** [comment]
For all it matters, I have used this PR and it solved a lot of some issues I had. I found it rather straight forward to use (just set the option and the `input$tree` will update on refresh. I think the easiest to see is to have an app which uses `input$tree` and without the option set it gets updated only after one alters the tree (like opening a node). With the option set it gets updated already at the beginning. 

I agree that there should be an example. If I am back from vacation I could help.

**Pull request merged**
